config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   root "pages#home"
   post "/process_payment", to: "pages#process_payment", as: "payment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create_commit :add_customer_id


  def add_customer_id
    if  self.customer_id.nil?
    customer = Stripe::Customer.create(
              :email => self.email
            )

    self.customer_id = customer.id
    self.save
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   before_action :authenticate_user!
    
    def home
        @user = current_user
    end

        def process_payment
            # Amount in cents
            @amount = 500
          
            # customer = Stripe::Customer.create(
            #   :email => params[:stripeEmail],
            #   :source  => params[:stripeToken]
            # )

            customer = Stripe::Customer.retrieve(current_user.customer_id)
            customer.source = params[:stripeToken]
            customer.save
          
            charge = Stripe::Charge.create(
              :customer   => current_user.customer_id,
              :amount      => @amount,
              :description => 'Rails Stripe customer',
              :currency    => 'aud'
            )
          
            redirect to "/"

          rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to new_charge_path
          end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Home page </h>

<%= form_with url: payment_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>
  
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.application.credentials.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto">
            data-email="<%= @user.email %>"</script>
  <% end %>